[template]
cargo_generate_version = ">=0.20.0"

[hooks]
pre = ["pre-script.rhai"]

[placeholders.mcu]
type    = "string"
prompt  = "Which MCU to target?"
choices = ["esp32", "esp32c2", "esp32c3", "esp32c6", "esp32h2", "esp32s2", "esp32s3"]
default = "esp32"
