# Edition
edition = "2021"

# Comments
format_code_in_doc_comments = true
normalize_comments          = true
wrap_comments               = true

# Imports
group_imports       = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout      = "HorizontalVertical"

# Miscellaneous
enum_discrim_align_threshold = 25
hex_literal_case             = "Upper"
